#! /bin/csh -f
#
# RHO       = DENSITY
# MBOX      = BOX CONSTANT
# NSTEP     = NUMBER OF TIMESTEPS
# NINIT     = NUMBER OF INITIALIZATION STEPS
# TEMP      = TEMPERATURE
# DELTAT    = TIMESTEP FOR INTEGRATION

set RHO     = 0.82
set MBOX    = 5
set NSTEP   = 500000
set TEMP    = 0.71
set DAMP    = 0.01
set DELTAT  = 0.005
set EQSTEPS = 500000
set MASS    = 1
set INIVEL  = 12
set CUTOFF  = 2.5
set ECUTOFF = 3.0
set DPROP   = 0.1
set SKIN    = 2
set LABEL   = 'T1_N5_RHO1'

# PRINT paramters
set eqVerboseFrame          = 100;

# TEMP paramters
set temperature_writeFrame  = 2000;

# VACF parameters
set vacf_writeFrame         = 100000;
set maxVACFCount            = 100;
set vacfSamplingReps        = 10;

# MSD parameters
set msd_writeFrame          = 100000;
set maxMSDCount             = 100;
set msdSamplingReps         = 10;

# RDF parameters
set RDF_writeFrame          = 50000;
set maxDistance             = 2.5; 
set numBins                 = 200; 

cat > input << endofdata
$RHO    $MBOX   $NSTEP  $TEMP  $DAMP  $DELTAT $EQSTEPS $MASS   $INIVEL    $CUTOFF   $ECUTOFF $DPROP $SKIN $LABEL
endofdata

cat > write_input << endofdata
$RDF_writeFrame $temperature_writeFrame $eqVerboseFrame  $vacf_writeFrame  $maxVACFCount  $vacfSamplingReps $msd_writeFrame $maxMSDCount   $msdSamplingReps    $maxDistance $numBins
endofdata

mkdir ../output_files/${LABEL}
time ../scripts/simul.exe
rm input
rm write_input
exit
