#! /bin/csh -f
#
# BOX      = BOXLENGTH
# NPART    = NUMBER OF PARTICLES
# NSTEP    = NUMBER OF TIMESTEPS
# NINIT    = NUMBER OF INITIALIZATION STEPS
# TEMP     = TEMPERATURE
# DELTAT   = TIMESTEP FOR INTEGRATION

set RHO     = 0.5
set MBOX    = 5
set NSTEP   = 1
set TEMP    = 0.1
set DAMP    = 0.5
set DELTAT  = 0.001
set EQSTEPS = 20000
set MASS    = 1
set INIVEL  = 15
set CUTOFF  = 2.5
set ECUTOFF = 2.5
set DPROP   = 0.5
set SKIN    = 6.349604
set LABEL   = 'T1_N5_RHO1'

# PRINT paramters
set eqVerboseFrame          = 100;

# TEMP paramters
set temperature_writeFrame  = 2000;

# VACF parameters
set vacf_writeFrame         = 1000;
set maxVACFCount            = 10;
set vacfSamplingReps        = 10;

# MSD parameters
set msd_writeFrame          = 1000;
set maxMSDCount             = 10;
set msdSamplingReps         = 10;

# RDF parameters
set RDF_writeFrame          = 100;
set maxDistance             = 10; 
set numBins                 = 1000; 


mkdir ../output_files/${LABEL}

cat > input << endofdata
$RHO    $MBOX   $NSTEP  $TEMP  $DAMP  $DELTAT $EQSTEPS $MASS   $INIVEL    $CUTOFF   $ECUTOFF $DPROP $SKIN $LABEL
endofdata

cat > write_input << endofdata
$RDF_writeFrame $temperature_writeFrame $eqVerboseFrame  $vacf_writeFrame  $maxVACFCount  $vacfSamplingReps $msd_writeFrame $maxMSDCount   $msdSamplingReps    $maxDistance $numBins
endofdata

time ../scripts/simul.exe
rm input
rm write_input
exit
